### ISSUE TITLE
Hide if all "All Good"

### ISSUE THREAD

**Issue by dmarkscouk** [nigel-daniels/MMM-Tube-Status#1]
Nice Module :)
It would be great to be able to hide the module entirely if all services are "Good Service". (Including the module title.

**Comment by nigel-daniels** [comment]
Thanks!
I was thinking of adding a single line to state all lines are good if there are no delays and show_all is set to false.  It does look a bit odd if a heading is used with show_all set to false and there is nothing to report.

**Comment by nigel-daniels** [comment]
oops hit wrong button, I did not mean to close this, please add further comments if you wish!

**Comment by dmarkscouk** [comment]
This sounds like a good alternative to me. I tried to have a go at implementing this, but just ended up breaking the module.

**Comment by nigel-daniels** [comment]
Done under commit 7f2d32d.

**Comment by dmarkscouk** [comment]
Thanks for the reply. This is a nice feature :)
